"""SQLGlot-based SQL validation service for production Text-to-SQL systems.

Provides a complete validation pipeline:
  1. Basic sanity checks (empty query, length limit).
  2. AST parsing via SQLGlot (PostgreSQL dialect).
  3. Multiple-statement detection (e.g. SELECT …; DROP TABLE …).
  4. Forbidden statement type enforcement (INSERT, UPDATE, DELETE, DROP, …).
  5. SELECT-only enforcement.
  6. Query complexity checks (max JOINs, max nested subqueries).
  7. Table and column extraction from the AST.
  8. Schema whitelist validation — detects hallucinated tables and columns.
  9. Automatic LIMIT injection when no LIMIT clause is present.

Public API
----------
validate_sql(sql, schema_metadata, *, max_joins, max_subqueries,
             max_query_length, auto_limit) -> ValidationResult
extract_tables(statement) -> list[str]
extract_columns(statement) -> list[str]
apply_limit(statement, limit) -> str
check_complexity(statement, *, max_joins, max_subqueries) -> list[str]
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

import sqlglot
import sqlglot.expressions as exp

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Forbidden statement types
# ---------------------------------------------------------------------------

_FORBIDDEN_TYPES: dict[type[exp.Expression], str] = {
    exp.Insert: "INSERT",
    exp.Update: "UPDATE",
    exp.Delete: "DELETE",
    exp.Drop: "DROP",
    exp.Alter: "ALTER",
    exp.Create: "CREATE",
    exp.TruncateTable: "TRUNCATE",
    exp.Merge: "MERGE",
    exp.Command: "EXECUTE/CALL",
}


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class ValidationResult:
    """Complete result of the SQL validation pipeline."""

    is_valid: bool
    tables: list[str] = field(default_factory=list)
    columns: list[str] = field(default_factory=list)
    final_sql: str = ""
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "is_valid": self.is_valid,
            "tables": self.tables,
            "columns": self.columns,
            "final_sql": self.final_sql,
            "errors": self.errors,
        }


# ---------------------------------------------------------------------------
# Main validation entry point
# ---------------------------------------------------------------------------

def validate_sql(
    sql: str,
    schema_metadata: dict[str, list[str]] | None = None,
    *,
    max_joins: int = 10,
    max_subqueries: int = 5,
    max_query_length: int = 8000,
    auto_limit: int = 500,
) -> ValidationResult:
    """Run the full SQL validation pipeline.

    Args:
        sql:             Raw SQL string generated by the LLM.
        schema_metadata: Optional ``{table_name_lower: [column_names_lower]}``
                         dict used for hallucination detection.
        max_joins:       Maximum allowed JOIN clauses (default 10).
        max_subqueries:  Maximum allowed nested subqueries (default 5).
        max_query_length: Maximum character length for the SQL string (default 8000).
        auto_limit:      Row cap injected when no LIMIT exists; 0 disables (default 500).

    Returns:
        :class:`ValidationResult` with ``is_valid``, ``tables``, ``columns``,
        ``final_sql``, and ``errors``.
    """
    logger.info("=== SQLGlot Validation ===")
    logger.info("Original SQL (first 300 chars): %s", sql.strip()[:300])

    result = ValidationResult(is_valid=False, final_sql=sql.strip())

    # ── 1. Basic sanity checks ────────────────────────────────────────────────
    cleaned = sql.strip()
    if not cleaned:
        result.errors.append("No SQL query was generated.")
        return result

    if len(cleaned) > max_query_length:
        result.errors.append(
            f"SQL query exceeds the maximum allowed length of {max_query_length} "
            f"characters (received {len(cleaned)})."
        )
        return result

    # ── 2. SQLGlot AST parsing ────────────────────────────────────────────────
    try:
        statements = sqlglot.parse(cleaned, dialect="postgres")
    except sqlglot.errors.ParseError as exc:
        result.errors.append(f"SQL parse error: {exc}")
        logger.warning("SQLGlot parse error: %s", exc)
        return result

    if not statements:
        result.errors.append("Could not parse SQL — no valid statements found.")
        return result

    # Filter out None entries produced by trailing semicolons.
    statements = [s for s in statements if s is not None]
    if not statements:
        result.errors.append("Could not parse SQL — no valid statements found.")
        return result

    logger.info("Parsed AST: %d statement(s) found.", len(statements))

    # ── 3. Multiple-statement detection ──────────────────────────────────────
    if len(statements) > 1:
        type_names = [type(s).__name__ for s in statements]
        result.errors.append(
            f"Multiple SQL statements detected ({len(statements)} statements: "
            f"{', '.join(type_names)}). Only a single SELECT statement is permitted."
        )
        logger.warning("Multiple statements blocked: %s", type_names)
        return result

    statement = statements[0]
    logger.info("AST root type: %s", type(statement).__name__)

    # ── 4. Forbidden statement type check ─────────────────────────────────────
    for forbidden_cls, label in _FORBIDDEN_TYPES.items():
        if isinstance(statement, forbidden_cls):
            result.errors.append(
                f"Forbidden SQL operation '{label}' detected. "
                "Only SELECT queries are permitted."
            )
            logger.warning("Blocked forbidden statement: %s", label)
            return result

    # ── 5. SELECT-only enforcement ────────────────────────────────────────────
    # After the forbidden-type filter, anything that isn't a SELECT / set-op
    # is still rejected.
    _SELECT_TYPES = (exp.Select, exp.Union, exp.Intersect, exp.Except)
    if not isinstance(statement, _SELECT_TYPES):
        result.errors.append(
            f"Statement type '{type(statement).__name__}' is not allowed. "
            "Only SELECT queries are permitted."
        )
        logger.warning("Non-SELECT statement blocked: %s", type(statement).__name__)
        return result

    # ── 6. Complexity checks ───────────────────────────────────────────────────
    complexity_errors = check_complexity(
        statement,
        max_joins=max_joins,
        max_subqueries=max_subqueries,
    )
    if complexity_errors:
        result.errors.extend(complexity_errors)
        return result

    # ── 7. Table and column extraction ────────────────────────────────────────
    tables = extract_tables(statement)
    columns = extract_columns(statement)
    result.tables = tables
    result.columns = columns

    logger.info("Tables referenced: %s", tables)
    logger.info("Columns referenced: %s", columns)

    # ── 8. Schema validation (hallucination detection) ────────────────────────
    if schema_metadata:
        schema_errors = _validate_against_schema(statement, tables, columns, schema_metadata)
        if schema_errors:
            result.errors.extend(schema_errors)
            return result
    else:
        logger.debug("Schema validation skipped (no metadata provided).")

    # ── 9. Auto LIMIT injection ────────────────────────────────────────────────
    final_sql = apply_limit(statement, auto_limit) if auto_limit > 0 else cleaned
    result.final_sql = final_sql
    result.is_valid = True

    logger.info("Validation passed. Final SQL (first 300 chars): %s", final_sql[:300])
    return result


# ---------------------------------------------------------------------------
# Public helper functions
# ---------------------------------------------------------------------------

def extract_tables(statement: exp.Expression) -> list[str]:
    """Return a deduplicated, lowercase list of table names referenced in *statement*.

    Schema-qualifiers (e.g. ``public.my_table``) are stripped — only the
    bare table name is returned.
    """
    seen: set[str] = set()
    tables: list[str] = []
    for table_node in statement.find_all(exp.Table):
        name = table_node.name
        if name:
            lower = name.lower()
            if lower not in seen:
                seen.add(lower)
                tables.append(lower)
    return tables


def extract_columns(statement: exp.Expression) -> list[str]:
    """Return a deduplicated, lowercase list of column names referenced in *statement*.

    Wildcard ``*`` is excluded.  Table-qualifiers and aliases are stripped.
    """
    seen: set[str] = set()
    columns: list[str] = []
    for col_node in statement.find_all(exp.Column):
        name = col_node.name
        if name and name != "*":
            lower = name.lower()
            if lower not in seen:
                seen.add(lower)
                columns.append(lower)
    return columns


def apply_limit(statement: exp.Expression, limit: int = 500) -> str:
    """Return the SQL string with *limit* appended when no LIMIT clause exists.

    For :class:`~sqlglot.expressions.Select` nodes the LIMIT is injected into
    the AST and the query is re-serialised via SQLGlot (preserving formatting).
    For set-operation nodes (UNION / INTERSECT / EXCEPT) the LIMIT is appended
    as plain text, which is valid PostgreSQL syntax.
    """
    # If a LIMIT already exists on the outermost node, return as-is.
    if statement.args.get("limit") is not None:
        logger.debug("LIMIT already present — not injecting.")
        return statement.sql(dialect="postgres")

    if isinstance(statement, exp.Select):
        modified = statement.copy()
        modified.set("limit", exp.Limit(expression=exp.Literal.number(limit)))
        sql_out = modified.sql(dialect="postgres")
        logger.info("Auto-injected LIMIT %d.", limit)
        return sql_out

    # UNION / INTERSECT / EXCEPT — append in text form.
    base_sql = statement.sql(dialect="postgres")
    sql_out = f"{base_sql} LIMIT {limit}"
    logger.info("Auto-injected LIMIT %d (set-operation query).", limit)
    return sql_out


def check_complexity(
    statement: exp.Expression,
    *,
    max_joins: int = 10,
    max_subqueries: int = 5,
) -> list[str]:
    """Check query complexity and return a list of error messages (empty list = OK).

    Checks performed:

    * **JOIN count** — counts every :class:`~sqlglot.expressions.Join` node
      recursively, including those inside subqueries.
    * **Nested subquery count** — counts
      :class:`~sqlglot.expressions.Subquery` nodes (i.e. SELECTs that appear
      as derived tables or correlated subqueries), excluding the outermost
      statement itself.
    """
    errors: list[str] = []

    # Join count (recursive — catches joins inside subqueries too)
    join_count = len(list(statement.find_all(exp.Join)))
    if join_count > max_joins:
        errors.append(
            f"Query complexity too high: {join_count} JOIN clause(s) found "
            f"(maximum allowed: {max_joins})."
        )
        logger.warning("Complexity: %d JOINs exceeds limit %d.", join_count, max_joins)

    # Subquery count — use exp.Subquery which specifically wraps nested selects.
    subquery_count = len(list(statement.find_all(exp.Subquery)))
    if subquery_count > max_subqueries:
        errors.append(
            f"Query complexity too high: {subquery_count} nested subquery/subqueries "
            f"found (maximum allowed: {max_subqueries})."
        )
        logger.warning(
            "Complexity: %d subqueries exceeds limit %d.",
            subquery_count,
            max_subqueries,
        )

    return errors


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _validate_against_schema(
    statement: exp.Expression,
    tables: list[str],
    columns: list[str],  # noqa: ARG001 — kept for API symmetry; detailed check uses AST
    schema_metadata: dict[str, list[str]],
) -> list[str]:
    """Validate referenced tables and columns against *schema_metadata*.

    *schema_metadata* must have lowercase keys and lowercase column lists.

    CTE names are collected from the AST and treated as valid table references
    so that ``WITH cte AS (…) SELECT * FROM cte`` is not incorrectly flagged.
    """
    errors: list[str] = []
    known_tables: set[str] = set(schema_metadata.keys())

    # ── Collect CTE names (they are valid table references) ────────────────
    cte_names: set[str] = {
        cte.alias_or_name.lower()
        for cte in statement.find_all(exp.CTE)
    }

    # ── Table hallucination check ──────────────────────────────────────────
    hallucinated_tables = [
        t for t in tables if t not in known_tables and t not in cte_names
    ]
    if hallucinated_tables:
        errors.append(
            "Query references table(s) that do not exist in the database: "
            f"{', '.join(hallucinated_tables)}. "
            "Possible hallucination — please rephrase your question."
        )
        logger.warning("Hallucinated tables detected: %s", hallucinated_tables)
        # No point validating columns if tables are wrong.
        return errors

    # ── Build the set of all valid columns across referenced tables ─────────
    # Also include columns from CTEs (we don't have their schema, so skip CTE refs).
    valid_tables_for_cols = [t for t in tables if t in known_tables]
    all_valid_columns: set[str] = set()
    for tbl in valid_tables_for_cols:
        all_valid_columns.update(schema_metadata.get(tbl, []))

    # ── Column hallucination check (AST-level for qualified col refs) ──────
    hallucinated: list[str] = []

    for col_node in statement.find_all(exp.Column):
        col_name = col_node.name.lower() if col_node.name else ""
        if not col_name or col_name == "*":
            continue

        table_ref = col_node.table.lower() if col_node.table else None

        if table_ref:
            # Table-qualified column — skip if referencing a CTE or unknown table
            if table_ref in cte_names or table_ref not in known_tables:
                continue
            valid_cols = schema_metadata.get(table_ref, [])
            if col_name not in valid_cols:
                qualified = f"{table_ref}.{col_name}"
                if qualified not in hallucinated:
                    hallucinated.append(qualified)
        else:
            # Unqualified — must exist in at least one referenced table
            if col_name not in all_valid_columns:
                if col_name not in hallucinated:
                    hallucinated.append(col_name)

    if hallucinated:
        errors.append(
            "Query references column(s) that do not exist in the database: "
            f"{', '.join(hallucinated)}. "
            "Possible hallucination — please rephrase your question."
        )
        logger.warning("Hallucinated columns detected: %s", hallucinated)

    return errors
